---
- name: debian | installing glusterfs server
  apt:
    name: "glusterfs-server"
    state: present

- name: config_glusterfs_server | reconfiguring /etc/init/mounting-glusterfs.conf to start earlier on boot
  template:
    src: "etc/init/mounting-glusterfs.conf.j2"
    dest: "/etc/init/mounting-glusterfs.conf"
    owner: root
    group: root
    mode: 0644

- name: config_glusterfs_server | starting GlusterFS
  service:
    name: "glusterfs-server"
    state: started
    enabled: true

- name: config_glusterfs_server | connecting gluster peers
  shell: gluster peer probe {{ item }}
  register: gluster_peer_probe
  changed_when: "'already in peer list' not in gluster_peer_probe.stdout"
  ignore_errors: true  #added temporarily to get around Vagrant testing...may remove later
  with_items: '{{ groups[glusterfs_server_group] }}'
  when: item != inventory_hostname

- name: config_glusterfs_server | creating brick folders
  file:
    path: "{{ glusterfs_brick_dir }}/{{ item.name }}/"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: directory
  with_items: '{{ glusterfs_create_bricks }}'

- name: config_glusterfs_server | create gluster volume
  gluster_volume:
    state: present
    name: "{{ item.name }}"
    brick: "{{ glusterfs_brick_dir }}/{{ item.name }}"
    replicas: "{{ groups[glusterfs_server_group]|length }}"
    cluster: "{% for host in groups[glusterfs_server_group] %}{{ host }}{% if not loop.last %},{% endif %}{% endfor %}"
  with_items: '{{ glusterfs_create_bricks }}'
  when: inventory_hostname == glusterfs_server_master

- name: debian | enabling glusterfs-server
  service:
    name: "glusterfs-server"
    enabled: yes
